### ISSUE TITLE
Fix choice of language

### ISSUE THREAD

**Issue by ArthurGossel1** [ArthurGossel1/deep-translator-website#14]
# Expected Behavior

When we choose destination language, it should always be the choosen when for the traduction 

# Current Behavior

When you change destination language, and you loose focus on the first block, it's reset to english

## Steps to Reproduce

1. Choose destination language (other than english)
2. Go back to first block, write something
3. Destination language is set to English again

**Comment by TonyBionda** [comment]
Close, fixed in #35
