### ISSUE TITLE
Feature compare different translators

### ISSUE THREAD

**Issue by ArthurGossel1** [ArthurGossel1/deep-translator-website#24]
##New feature : 

Comparing translations. 

For example you translate one sentence with GoogleTraduction. 
You could click on "Compare" button, select with which translater you want to compare and it will show different translation for the same sentence. 

Exemple : 

1. Translater by default : Google Traduction 

From French : Bonjour à tout le monde  --> To English : Hello Everyone

2. Click on compare 
3. Show translations with all translators for : "From French : Bonjour à tout le monde  --> To English"

**Comment by TonyBionda** [comment]
Close
